### ISSUE TITLE
Entry Type not nesting

### ISSUE THREAD

**Issue by martinsmith** [mmikkel/ChildMe-Craft#8]
Hello,
When using the + symbol to add an Entry Type the new entry (when saved) is defaulting to Level 1 instead of nesting into Level 2.

**Comment by mmikkel** [comment]
Hi @martinsmith, thanks for reporting.

I think this is a bug in Craft, as I'm seeing the same behaviour when I use the native "New Entry" button, and manually select a parent in the Parent field (i.e. instead of using the Child Me! + button to create a child entry. The new entry is created at level 1 at the bottom of the Structure when saved, rather than being nested under the selected parent.

Can you test the native "New Entry" and parent fields and confirm if you're seeing the same as me? Also, great if you can tell me which Craft and Child Me! versions you're currently using.

**Comment by mmikkel** [comment]
Did some further testing and I'm almost positive this is a [Craft bug](https://github.com/craftcms/cms/issues/6168).

**Comment by mmikkel** [comment]
Confirmed bug in Craft 3.4.22.1. Fixed in the next release, closing this.
